



POST http://penta.store:3000/user/register
Content-Type: application/json

{
    "username": "jefyoktasaddfdsadsadsfsfsdcdczxcx",
    "email" : "memekdasdasfsddasdsarfdsdfsfdasd2",
    "password" : "123",
    "nama" :"jefyoktajbj"
   
}

###
POST  http://penta.store:3000/user/passv
Content-Type: application/json

{
    "username": "jefyokta",
    "password": "123"
}


###
GET http://localhost:3000/product?limit=21
###``


GET http://localhost:3000/user?u=jefyokta
###
GET http://localhost:3000/product

###
GET http://penta.store:3000/product/search?q=p

###
DELETE  http://penta.store:3000/user/logout

###
GET http://localhost:3000/order
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDk2NDA4NDMsImV4cCI6MTcwOTY0MDg2M30.2kAs7L1Bwk2oPYX38Attx92kuRLlQojDBLZqm8KfTQs
###
GET http://penta.store:3000/token

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlcm5hbWUiOiJqZWZ5b2t0YSIsImVtYWlsIjoiamVmeW9rdGE1MEBpY2xvdWQuY29tIiwiZ2FtYmFyIjoiNjU4YzBmNDc5NjJjNS5qcGciLCJyb2xlIjoxLCJpYXQiOjE3MTMzNjYyMzUsImV4cCI6MTcxMzM2NjI1NX0.YJ0SaNuSsqnkGYyyzrShZ0a0ACQvxhx0rFqkMC7wyGU.eyJpYXQiOjE3MDk2NDA4NDMsImV4cCI6MTcwOTY0MDg2M30.2kAs7L1Bwk2oPYX38Attx92kuRLlQojDBLZqm8KfTQs


###
GET http://localhost:3000/midtrans
Content-Type: application/json




###
POST http://penta.store:3000/user/login
Content-Type: application/json

{
    "username": "jefyokta",
    "password": "123"
}
###
POST http://penta.store:3000/transaction
Content-Type: application/json


{
  "product": "dskaodkoa",
  "id": 76,
  "harga": 10000,
  "name": "jepi",
  "email": "serah@gmail.com"
}


###
GET  http://penta.store:3000/product




###
GET https://pentastore.rf.gd/public/test?id=2 HTTP/1.1


###
GET http://penta.store:3000/rating?productid=105 HTTP/1.1



###
DELETE  http://penta.store:3000/user/logout HTTP/1.1
Content-Type: application/json

{
    "order_id":"order21",
    "status_code":"dtatuscode"
}

### 
GET http://penta.store:3000/transaction/userorder?userid=5 HTTP/1.1

###
GET http://penta.store:3000/user/mydata HTTP/1.1

###


POST http://penta.store:3000/user/updatephotodefault
Content-Type: application/json

{

      "gambar": "gfdkslk",

}

###
https://pentatransaction.vercel.app/order?id=23bcbd00-5d3b-4f11-b854-4402251e9904



