



POST https://api.penta.store/user/register
Content-Type: application/json

{
    "username": "jefyokta",
    "password": "123"
}
###

POST https://api.penta.store/user/login
Content-Type: application/json

{
    "username": "jefyokta",
    "password": "123"
}
###
GET https://api.penta.store/product
###


GET https://api.penta.store/user?u=jefyokta
